version: "3"
services:
  # lambda:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports: 
  #     - 8000:8888
  #   volumes: 
  #     - .:/app
      
  #   depends_on: 
  #     - db
  DB:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=lambdaDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - DB

  redisDB:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./d–∞ta:/root/redis
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redisDB:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redisDB
