# import * from "./types/user.gql"
# import * from "./types/token.gql"
type ids{
    id:ID
}
input login{
    email:String,
    password:String
}
type Query {
    USERS_GET(input:auth):User,
}
type Mutation {
 USER_CREATE(user_name: String
  email: String
  img: String
  password: String):ids,
 VERIFY_EMAIL(otp:String,id:ID):Token,
 LOGIN(email:String,password:String):Token
}
