# import * from "./types/user.gql"
# import * from "./types/token.gql"
# import * from "./types/offer.gql"
# import * from "./types/inputs.gql"
# import * from "./types/product.gql"
# import * from "./types/category.gql"
# import * from "./types/review.gql"




type Query {
	USERS_GET(input: AuthInp): [User],
	USER_GET(input: AuthInp): User,
	OFFERS_GET(input:offerInp): [Offer],
	PRODUCTS_GET(input:prodsInp):[Product],
	PRODUCT_GET(input:prodInp):Product,
	GET_CATEGORY(input:CategInp):category,
	GET_CATEGORYS(input:CategsInp):[category],
	GET_PRODUCT_REVIEWS(input:GetReviewsInp):review


}
type Mutation {
	USER_CREATE(input: UserInp):Id, 
	VERIFY_EMAIL(input: verifyInp): Token, 
	LOGIN(input: LoginInp): Token,
	ADD_TO_CART(input: AddCrtInp):String,
	RATE_PRODUCT(input:ReatingInp):String


}