input AuthInp {
     id:ID,
    token:String,
}

input UserInp {
  user_name: String                                                                                                
  email: String
  password: String
  img: String
}

input LoginInp {
	email: String, 
	password: String
}

input verifyInp {
    id:ID
    otp:String
}

input offerInp {
  usr_id:ID
  usr_token:String
}

input AddCrtInp {
  usr_id: ID
  token: String
  product_id: ID
}

input CategInp {
  Categ_name:String
  usr_id:ID
  usr_token:String
}

input CategsInp {
  usr_id:ID
  usr_token:String
}

input prodInp{
	id:ID
}

input prodsInp{
  filter: String
  orderByName:Sort
  byCategory:String

}
enum Sort {
  asc
  desc
}
