input AuthInp {
     id:ID,
    token:String,
}

input UserInp {
  user_name: String                                                                                                
  email: String
  password: String
  img: String
}

input LoginInp {
	email: String, 
	password: String
}

input verifyInp {
    id:ID
    otp:String
}

input offerInp {
  usr_id:ID
  usr_token:String
}

input AddCrtInp {
  usr_id: ID
  token: String
  product_id: ID
}

input CategInp {
  Categ_name:String
  
}



input prodInp{
	id:ID
}

input prodsInp{
  filter: String
  orderByName:Sort
  byCategory:String

}
enum Sort {
  asc
  desc
}

input ReatingInp{
  reating:Int
  product_id:String
  user_id:String
}

input GetReviewsInp{
  Product_id:String
}


input getCartInp{
  usr_id:String


}
input addToCartInp{
  Product_id:String
  usr_id:String
 Product_count:Int
}
input addToWishListInp{
  Product_id:String
  usr_id:String
 
}
input removeProdInp{
Ids:[ID]
}

input createCategoryInp{
    name: String
    img: String

}
input createProductInp{
   name: String
    img: String
    price: Int
    count: Int
    is_available: Boolean
    desc: String
}
input createOfferInp{
    name: String
    img:String
}
input CategsInp{
  takeCount:Int
}
input isInWishInp{
  productId:ID
  usetId:ID
}

input removeFromWishListInp{
  Product_id:String
  usr_id:String
}

input getWishListInp{
  usr_id:String
}

input removeFromCartInp{
  Product_id:String
  usr_id:String
}